---

- name: set iptables file
  tags:
    - iptables
  become: True
  ansible.builtin.template:
    src: etc/sysconfig/iptables
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: 0600
  notify: iptables
