---

# Find.
# https://github.com/anchore/grype (statically linked)
# https://github.com/lunasec-io/lunasec/releases/ (statically linked)
# https://github.com/hillu/local-log4j-vuln-scanner (statically linked)
# https://github.com/logpresso/CVE-2021-44228-Scanner (dynamically linked)

# Scan.
# https://github.com/lfama/log4j_checker (untested)
# https://github.com/fullhunt/log4j-scan (tested, works)

# Upload.
- name: set log4shell file
  tags:
    - splunk
  become: True
  ansible.builtin.copy:
    src: opt/splunk/etc/system/local/user-seed.conf
    dest: /opt/splunk/etc/system/local/user-seed.conf
    owner: splunk
    group: splunk
  when:
    - ansible_local.splunk.general.installed | bool == False

# Scan.

# Log.

# Cleanup.

# Find.
$SPLUNK_HOME/bin/jars/vendors/spark
$SPLUNK_HOME/bin/jars/vendors/libs/splunk-library-javalogging-*.jar
$SPLUNK_HOME/bin/jars/thirdparty/hive*
$SPLUNK_HOME/etc/apps/splunk_archiver/java-bin/jars/*

# Report.
