---

- name: set facts config
  tags:
    - facts
  ansible.builtin.include_tasks: facts.yml

- name: set vars config
  tags:
    - vars
  ansible.builtin.include_tasks: vars.yml

- name: get vars debug
  tags:
    - never
  ansible.builtin.include_tasks: debug.yml

- name: set packages install
  tags:
    - packages
  ansible.builtin.include_tasks: "packages-{{ ansible_os_family }}.yml"

- name: set hostname config
  tags:
    - hostname
  ansible.builtin.include_tasks: hostname.yml

- name: set users config
  tags:
    - users
  ansible.builtin.include_tasks: users.yml

- name: set sudo config
  tags:
    - sudo
  ansible.builtin.include_tasks: sudo.yml

- name: set aliases config
  tags:
    - aliases
  ansible.builtin.include_tasks: aliases.yml

- name: set iptables config
  tags:
    - iptables
  ansible.builtin.include_tasks: iptables.yml

- name: set openssh config
  tags:
    - openssh
  ansible.builtin.include_tasks: openssh.yml

- name: set postfix config
  tags:
    - postfix
  ansible.builtin.include_tasks: postfix.yml

- name: set services config
  tags:
    - services
  ansible.builtin.include_tasks: services.yml

- name: set SELinux config
  tags:
    - selinux
  ansible.builtin.include_tasks: selinux.yml

- name: set GRUB config
  tags:
    - grub
  ansible.builtin.include_tasks: grub.yml
