---

- name: set install epel-release
  become: True
  ansible.builtin.yum:
    name: epel-release
    update_cache: True
    state: latest

- name: set install packages
  become: True
  ansible.builtin.yum:
    name: "{{ baseline.packages.install }}"
    update_cache: True
    state: latest

- name: set remove packages
  become: True
  ansible.builtin.yum:
    name: "{{ baseline.packages.remove }}"
    update_cache: True
    state: absent
