---

- name: set install epel-release
  become: True
  ansible.builtin.yum:
    name: epel-release
    update_cache: True
    state: latest
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- name: set install packages
  become: True
  ansible.builtin.yum:
    name: "{{ baseline.packages.install }}"
    update_cache: True
    state: latest
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- name: set install epel-release
  become: True
  ansible.builtin.dnf:
    name: epel-release
    update_cache: True
    state: latest
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name: set install packages
  become: True
  ansible.builtin.dnf:
    name: "{{ baseline.packages.install }}"
    update_cache: True
    state: latest
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"
