---

# deps: facts, vars (OS et al.), users (splunk user/system account).

- name: set archive file
  tags:
    - splunk
  become: True
  ansible.builtin.unarchive:
    remote_src: True
    src: "{{ splunk.archive.file }}"
    dest: /opt
    owner: splunk
    group: splunk

# File is removed upon starting so not idempotent.
- name: set user-seed.conf file
  tags:
    - splunk
  become: True
  ansible.builtin.copy:
    src: opt/splunk/etc/system/local/user-seed.conf
    dest: /opt/splunk/etc/system/local/user-seed.conf
    owner: splunk
    group: splunk

- name: set splunk-launch.conf file
  tags:
    - splunk
  become: True
  ansible.builtin.template:
    src: opt/splunk/etc/splunk-launch.conf
    dest: /opt/splunk/etc/splunk-launch.conf
    owner: splunk
    group: splunk
  notify: splunk

# splunk enable boot-start -user splunk: /opt/splunk/etc/splunk-launch.conf (SPLUNK_OS_USER=splunk).
# robertg> /opt/splunk/bin/splunk start: "Failed to run splunk as SPLUNK_OS_USER. This command can only be run by bootstart user." (su - splunk (no passwd, wheel group)).
# splunk> /opt/splunk/bin/splunk start: ulimit applied.
# root> /opt/splunk/bin/splunk start: ulimit not applied.
# robertg> sudo -su splunk /opt/splunk/bin/splunk start: ulimit applied (/sbin/nologin works).
# any> systemctl start splunk.service: ulimit (LimitNOFILE=65536) applied.
# any> /opt/splunk/bin/splunk start: /etc/systemd/system/splunk.service is used!
# any> /etc/init.d/splunk start: uses systemctl.
# operator> sudo -iu splunk /opt/splunk/bin/splunk status: "Sorry, user slob is not allowed to execute '/sbin/nologin -c /opt/splunk/bin/splunk status' as splunk on spl-sh-mac01.ephemeric.lan.".
- name: set Systemd service
  tags:
    - splunk
  become: True
  environment:
    # Fixes: "Generating RSA private key, 2048 bit long modulus... unable to write 'random state'".
    RANDFILE: /opt/splunk/.rnd
  ansible.builtin.command:
    cmd: /opt/splunk/bin/splunk enable boot-start -systemd-managed 1 -user splunk -group splunk --accept-license --no-prompt --answer-yes
    creates: /etc/systemd/system/splunkd.service
  notify: splunk

- name: set install fact
  tags:
    - splunk
  become: True
  ansible.builtin.lineinfile:
    create: True
    path: /etc/ansible/facts.d/splunk.fact
    regexp: '^installed\s=\s.*$'
    line: 'installed = True'
