---

- name: set archive file
  tags:
    - splunk
  become: True
  ansible.builtin.unarchive:
    src: "{{ splunk.archive.file }}"
    dest: /opt
    owner: splunk
    group: splunk

- name: set user-seed.conf file
  tags:
    - splunk
  become: True
  ansible.builtin.copy:
    src: opt/splunk/etc/system/local/user-seed.conf
    dest: /opt/splunk/etc/system/local/user-seed.conf
    owner: splunk
    group: splunk

- name: set splunk-launch.conf file
  tags:
    - splunk
  become: True
  ansible.builtin.template:
    src: opt/splunk/etc/splunk-launch.conf
    dest: /opt/splunk/etc/splunk-launch.conf
    owner: splunk
    group: splunk
  notify: splunk

# Process: 6343 ExecStart=/etc/rc.d/init.d/splunk start (code=exited, status=0/SUCCESS): ulimit has no effect.
# splunk$> /opt/splunk/bin/splunk start: ulimit applied.
# systemctl start splunk.service: LimitNOFILE=65536 applied.
- name: set Systemd service
  tags:
    - splunk
  become: True
  environment:
    RANDFILE: /opt/splunk/.rnd
  ansible.builtin.command:
    # splunk start --accept-license  --no-prompt --answer-yes
    cmd: /opt/splunk/bin/splunk enable boot-start -systemd-managed 1 -user splunk -group splunk --accept-license 
    creates: /etc/systemd/system/splunkd.service
  notify: splunk

#- name: set Systemd file
#  tags:
#    - splunk
#become: True
#ansible.builtin.lineinfile:
  #backup: True
  #path: /etc/systemd/system/splunkd.service
  #regexp: '^ExecStart.*$'
  #line: '\1 --accept-license --no-prompt --answer-yes'
  #verify: systemd-analyze verify /etc/systemd/system/splunkd.service

- name: set install fact
  tags:
    - splunk
  become: True
  ansible.builtin.lineinfile:
    create: True
    path: /etc/ansible/facts.d/splunk.fact
    regexp: '^installed\s=\s.*$'
    line: 'installed = True'
