---

- name: set sudoers config
  tags: always
  become: True
  ansible.builtin.copy:
    content: "{{ item.sudoers }}"
    dest: "/etc/sudoers.d/{{ item.name }}"
    owner: root
    group: root
    mode: 0400
    validate: visudo -cf %s
  loop: "{{ baseline.users }}"
  when:
    - item.sudoers != False

#[root@splunk-01 ~]# su - -s /bin/bash splunk
#Last login: Tue Jul 26 10:48:01 UTC 2022 on pts/0
#-bash-4.2$ shopt | grep shell
#login_shell    	on
#restricted_shell	off
#
#[root@splunk-01 ~]# sudo -su splunk
#bash-4.2$ shopt | grep shell
#login_shell    	off
#restricted_shell	off
#
#splunk-01 :: ~ % su - -s /bin/bash splunk
#su: using restricted shell /sbin/nologin
#Last login: Tue Jul 26 10:54:09 UTC 2022 on pts/0
#This account is currently not available.
#
#splunk-01 :: ~ % sudo -su splunk
#This is the Z Shell configuration function for new users,...
#[splunk@splunk-01]/home/robertg% set -o | grep login
#login                 off
