---

- name: set user account
  tags:
    - users
  become: True
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid | default(omit) }}"
    home: "{{ item.home }}"
    shell: "{{ item.shell }}"
    create_home: "{{ item.create_home }}"
    system: "{{ item.system }}"
    state: "{{ item.state }}"
    groups: "{{ item.groups }}"
    append: True
  loop: "{{ baseline.users }}"

- name: set user pubkey
  tags:
    - users
  become: True
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.authorized_key }}"
  loop: "{{ baseline.users }}"
  when:
     - item.authorized_key != False
