---

- name: grub
  become: True
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: iptables
  become: True
  ansible.builtin.systemd:
    daemon_reload: True
    name: iptables
    enabled: True
    state: restarted

- name: openssh
  become: True
  ansible.builtin.systemd:
    daemon_reload: True
    name: sshd
    enabled: True
    state: restarted

- name: postfix
  become: True
  ansible.builtin.systemd:
    daemon_reload: True
    name: postfix
    enabled: True
    state: restarted
