---

- name: Create ad application
  hosts: localhost
  vars:
    display_name: "slobwashere"
  tasks:

  - name: Create ad application
    azure.azcollection.azure_rm_adapplication:
      display_name: "{{ display_name }}"
    delegate_to: localhost
