---

- name: set baseline config
  hosts: "{{ target_hosts | default('none') }}"
  gather_facts: False

  pre_tasks:
    - name: get limit arg
      tags:
        - always
      fail:
        msg: "usage: ansible-playbook playbooks/<playbook> -l|--limit"
      run_once: true
      when: ansible_limit is not defined

  roles:
    - baseline
