---

- name: set baseline config
  # TODO: target_hosts?
  #hosts: "{{ target_hosts | default('none') }}"
  hosts: all
  gather_facts: False

  pre_tasks:
    - name: get limit arg
      tags:
        - always
      debug:
        msg: "usage: ansible-playbook playbooks/<playbook> -l|--limit"
      run_once: true
      when: ansible_limit is not defined

  roles:
    - baseline
