---

- hosts: localhost

  vars:
    valid_values: [ true, false ]

    fruit: [ apple, banana, orange, grapes ]

    food: {}

    _postfix_daemon_directory:
      default:
        file: /usr/libexec/postfix
        slob:
          hello: /usr/libexec/postfix
        was: /usr/libexec/postfix
      Debian: /usr/lib/postfix/sbin
      Suse: /usr/lib/postfix/bin

    slobwashere:
      - one:
          hello: boss
          bye: you
      - two: gone
      - three: tomorrow

    slobwasthere:
      one: two
      me: him

    mydict:
      hello: world
      slob: islame
      my_list:
        - some: item
        - another: item

  tasks:
  - set_fact:
      food: "{{ food | combine({'fruit': 'apple'}) }}"

  - set_fact:
      food: "{{ food | combine({'veggie': 'tomato'}) }}"

  - name: output the contents of the 'fruit' list
    debug:
      #var: mydict.hello
      #var: slobwashere[1]
      #var: slobwashere
      #var: slobwashere.one
      #var: slobwasthere
      #var: mydict.my_list # "VARIABLE IS NOT DEFINED!"
      #var: mydict.my_list[1]
      #var: fruit
      #var: slobwashere
      #var: food
      #var: valid_values
      var: _postfix_daemon_directory['default'].slob.hello
      #var: _postfix_daemon_directory.default # "VARIABLE IS NOT DEFINED!"
      #var: _postfix_daemon_directory[default] # "VARIABLE IS NOT DEFINED!"

#ok: [localhost] => {
#    "slobwashere": [
#        "one",
#        "two",
#        "three"
#    ]
#}

#ok: [localhost] => {
#    "fruit": [
#        "apple",
#        "banana",
#        "orange",
#        "grapes"
#    ]
#}
