---

- name: set baseline config
  hosts: "{{ ansible_limit | default('use-lor--limit') }}"
  gather_facts: False

  tasks:

  - name: shell command
    shell: ls -al /tmp
    register: myshell_output
    delegate_to: localhost

  - name: local file
    copy:
      content: "{{ myshell_output.stdout_lines }}"
      dest: "/tmp/slobwashere"
    delegate_to: localhost
