---

- name: set baseline config
  #hosts: "{{ ansible_limit | default('use-lor--limit') }}"
  hosts: "{{ ansible_limit | default('none') }}"
  gather_facts: False

  pre_tasks:
    - name: get limit arg
      tags:
        - always
      debug:
        msg: "usage: ansible-playbook playbooks/<playbook> -l|--limit"
      run_once: true
      #when: ansible_limit is not defined

  tasks:
  - name: shell command
    shell: ls -al /tmp
    register: myshell_output
    delegate_to: localhost

  - name: local file
    copy:
      content: "{{ myshell_output.stdout_lines }}"
      dest: "/tmp/slobwashere"
    delegate_to: localhost

  #- name: get tarball
  #get_url:
  #url: https://download.splunk.com/products/splunk/releases/8.2.5/linux/splunk-8.2.5-77015bc7a462-Linux-x86_64.tgz
  #dest: /tmp/splunk-8.2.5-77015bc7a462-Linux-x86_64.tgz
  #mode: '0440'
